#!/bin/sh

#nasm -o ./src/osloader.bin	./src/osloader.asm
#nasm -o ./src/bootMBR.bin ./src/bootMBR.asm

#nasm -f elf -o ./src/kernelex.o ./src/kernel.asm
#gcc -c -m32 -g -o ./src/start.o ./src/start.c
#ld -Ttext 0x30400  -m elf_i386 -o ./src/kernelex.elf ./src/kernelex.o ./src/start.o

umount /mnt/fat32/
mkfs.vfat -F 32 /dev/mapper/loop0p1
dd if=./boot/bootMBR.bin of=udisk.img bs=1 count=446 conv=notrunc
mount /dev/mapper/loop0p1 /mnt/fat32/
cp ./osloader/osloader.bin /mnt/fat32/
cp ./kernel/kernelex.elf /mnt/fat32/
cp ./test/TESTFILE	/mnt/fat32/
cp ./test/TESTCALL /mnt/fat32/
cp ./app/ECHO /mnt/fat32/
sync


